#!/usr/bin/env python3
"""
Analyze GF180 NMOS NFmin/JD sweep files for LNA pre-design.

The script reads the sweep text files generated by ngspice, combines them,
creates comparison plots, and writes plain-text summary reports with the best
bias points per device/topology/geometry.
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd
except ImportError as exc:
    missing = exc.name or "a required Python package"
    raise SystemExit(
        f"Missing Python package: {missing}\n"
        "Install the required packages with:\n"
        "  python3 -m pip install pandas numpy matplotlib\n"
        "or on Ubuntu/Debian:\n"
        "  sudo apt install python3-pandas python3-numpy python3-matplotlib"
    ) from exc


DEFAULT_FILENAMES = [
    "nmos06_cg_full_nom5v.txt",
    "nmos10_cg_full_nom5v.txt",
    "nmos06_cs_full_nom5v.txt",
    "nmos05_cg_full_nom5v.txt",
    "nmos10_cs_full_nom5v.txt",
    "nmos05_cs_full_nom5v.txt",
    "nmos03_cg_full_dense.txt",
    "nmos03_cs_full_dense.txt",
]

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
DEFAULT_RESULTS_DIR = PROJECT_DIR / "results"

DEFAULT_SEARCH_DIRS = [
    DEFAULT_RESULTS_DIR,
    Path.cwd() / "results",
    Path.cwd(),
    SCRIPT_DIR,
]


DEVICE_LABELS = {
    "03": "nfet_03v3",
    "05": "nfet_05v0",
    "06": "nfet_06v0",
    "10": "nfet_10v0_asym",
}

STYLE_MAP = {
    ("nfet_03v3", "CS"): {"color": "#1f77b4", "marker": "o"},
    ("nfet_03v3", "CG"): {"color": "#17becf", "marker": "s"},
    ("nfet_05v0", "CS"): {"color": "#ff7f0e", "marker": "o"},
    ("nfet_05v0", "CG"): {"color": "#d62728", "marker": "s"},
    ("nfet_06v0", "CS"): {"color": "#2ca02c", "marker": "o"},
    ("nfet_06v0", "CG"): {"color": "#9467bd", "marker": "s"},
    ("nfet_10v0_asym", "CS"): {"color": "#8c564b", "marker": "o"},
    ("nfet_10v0_asym", "CG"): {"color": "#e377c2", "marker": "s"},
}

DEFAULT_FILTERS = {
    "min_gm_s": 1e-3,
    "min_id_a": 10e-6,
    "min_pdc_mw": 0.01,
    "max_inv_gm_ohm": 1000.0,
    "cg_min_rin_ohm": 20.0,
    "cg_max_rin_ohm": 200.0,
}


def parse_name(path: Path) -> tuple[str, str]:
    match = re.search(r"nmos(\d+)_(cg|cs)", path.name.lower())
    if not match:
        return path.stem, "unknown"
    device_code, topology = match.groups()
    return DEVICE_LABELS.get(device_code, f"nmos{device_code}"), topology.upper()


def read_sweep(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(path)

    df = pd.read_csv(path, sep=r"\s+", comment="*", engine="python")
    device, topology = parse_name(path)
    df["device"] = device
    df["topology"] = topology
    df["source_file"] = path.name

    if "Rin_CG_est_Ohm" in df.columns:
        df["Rin_or_inv_gm_Ohm"] = df["Rin_CG_est_Ohm"]
    elif "inv_gm_Ohm" in df.columns:
        df["Rin_or_inv_gm_Ohm"] = df["inv_gm_Ohm"]
    else:
        df["Rin_or_inv_gm_Ohm"] = np.nan

    for col in df.columns:
        if col not in {"device", "topology", "source_file"}:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.replace([np.inf, -np.inf], np.nan)
    df = df.dropna(subset=["NFmin_dB", "JD_mA_per_um", "gm_ID_1_per_V", "gmro"])
    df = df[df["ID_A"] > 0]
    return df


def discover_default_files() -> list[Path]:
    for directory in DEFAULT_SEARCH_DIRS:
        paths = [directory / name for name in DEFAULT_FILENAMES]
        if all(path.exists() for path in paths):
            return paths

    missing_report = []
    for directory in DEFAULT_SEARCH_DIRS:
        missing = [name for name in DEFAULT_FILENAMES if not (directory / name).exists()]
        missing_report.append(f"{directory}: missing {len(missing)} files")
    raise SystemExit(
        "Could not find the eight default sweep files.\n"
        "Either run the script in the folder containing the .txt files, or pass the files manually.\n\n"
        + "\n".join(missing_report)
    )


def minmax(series: pd.Series) -> pd.Series:
    lo = series.min(skipna=True)
    hi = series.max(skipna=True)
    if not np.isfinite(lo) or not np.isfinite(hi) or math.isclose(lo, hi):
        return pd.Series(0.0, index=series.index)
    return (series - lo) / (hi - lo)


def add_scores(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    if "SOpt_mag" not in df.columns:
        df["SOpt_mag"] = np.sqrt(df["SOpt_real"] ** 2 + df["SOpt_imag"] ** 2)
    df["cg_50ohm_error"] = np.nan
    is_cg = df["topology"].eq("CG")
    df.loc[is_cg, "cg_50ohm_error"] = (
        (df.loc[is_cg, "Rin_or_inv_gm_Ohm"] - 50.0).abs() / 50.0
    )
    df["cg_50ohm_error"] = df["cg_50ohm_error"].fillna(0.0).clip(upper=5.0)
    df["sopt_edge_error"] = df["SOpt_mag"].clip(lower=0.0, upper=1.5)

    df["score"] = (
        0.45 * minmax(df["NFmin_dB"])
        + 0.20 * minmax(df["Pdc_mW"])
        + 0.15 * minmax(df["Rn_Ohm"])
        + 0.10 * minmax(df["cg_50ohm_error"])
        + 0.10 * minmax(-df["gm_ID_1_per_V"])
    )
    df["design_score"] = (
        0.35 * minmax(df["NF_dB"])
        + 0.25 * minmax(df["Pdc_mW"])
        + 0.15 * minmax(df["sopt_edge_error"])
        + 0.10 * minmax(df["Rn_Ohm"])
        + 0.10 * minmax(df["cg_50ohm_error"])
        + 0.05 * minmax(-df["gm_S"])
    )
    return df


def apply_lna_filter(
    df: pd.DataFrame,
    min_gm_s: float,
    min_id_a: float,
    min_pdc_mw: float,
    max_inv_gm_ohm: float,
    cg_min_rin_ohm: float,
    cg_max_rin_ohm: float,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    df = df.copy()
    df["filter_reason"] = "usable"

    near_off = (
        (df["gm_S"] < min_gm_s)
        | (df["ID_A"] < min_id_a)
        | (df["Pdc_mW"] < min_pdc_mw)
        | (df["Rin_or_inv_gm_Ohm"] > max_inv_gm_ohm)
    )
    df.loc[near_off, "filter_reason"] = "near_off_or_too_low_gm"

    is_cg = df["topology"].eq("CG")
    bad_cg_match = is_cg & (
        (df["Rin_or_inv_gm_Ohm"] < cg_min_rin_ohm)
        | (df["Rin_or_inv_gm_Ohm"] > cg_max_rin_ohm)
    )
    df.loc[bad_cg_match & ~near_off, "filter_reason"] = "cg_rin_not_near_50ohm"

    usable = df[df["filter_reason"].eq("usable")].copy()
    rejected = df[~df["filter_reason"].eq("usable")].copy()
    return usable, rejected


def style_for(device: str, topology: str) -> dict[str, object]:
    return STYLE_MAP.get((device, topology), {"color": "#333333", "marker": "o"})


def best_rows(df: pd.DataFrame, group_cols: list[str], metric: str) -> pd.DataFrame:
    if df.empty:
        return df.copy()
    idx = df.groupby(group_cols, dropna=False)[metric].idxmin()
    cols = [
        "device",
        "topology",
        "VDS_set_V",
        "W_m",
        "L_m",
        "VBIAS_set_V",
        "VGS_actual_V",
        "VDS_actual_V",
        "VBS_actual_V",
        "ID_A",
        "JD_mA_per_um",
        "Pdc_mW",
        "gm_S",
        "gds_S",
        "gm_ID_1_per_V",
        "ro_Ohm",
        "gmro",
        "Rin_or_inv_gm_Ohm",
        "NFmin_dB",
        "NF_dB",
        "Rn_Ohm",
        "SOpt_real",
        "SOpt_imag",
        "SOpt_mag",
        "cg_50ohm_error",
        "score",
        "design_score",
        "source_file",
    ]
    return df.loc[idx, [c for c in cols if c in df.columns]].sort_values(metric)


def save_fig(path: Path) -> None:
    plt.tight_layout()
    plt.savefig(path, dpi=180)
    plt.close()


def annotate_bars(ax, values: pd.Series, fmt: str = "{:.3g}") -> None:
    y_max = max(float(values.max()), 1e-12)
    ax.set_ylim(top=y_max * 1.18)
    for patch, value in zip(ax.patches, values):
        ax.annotate(
            fmt.format(value),
            (patch.get_x() + patch.get_width() / 2, patch.get_height()),
            ha="center",
            va="bottom",
            fontsize=8,
            rotation=0,
            xytext=(0, 3),
            textcoords="offset points",
        )


def plot_nfmin_vs_jd(df: pd.DataFrame, out_dir: Path, title_label: str) -> None:
    plt.figure(figsize=(10, 6))
    for (device, topology), sub in df.groupby(["device", "topology"]):
        label = f"{device} {topology}"
        style = style_for(device, topology)
        plt.scatter(
            sub["JD_mA_per_um"],
            sub["NFmin_dB"],
            s=24,
            alpha=0.85,
            edgecolors="none",
            color=style["color"],
            marker=style["marker"],
            label=label,
        )
    plt.xscale("log")
    plt.xlabel("JD (mA/um)")
    plt.ylabel("NFmin (dB)")
    plt.title(f"{title_label}: NFmin vs Current Density")
    plt.grid(True, which="both", alpha=0.35)
    plt.legend(fontsize=8, ncol=2)
    save_fig(out_dir / "01_nfmin_vs_jd_all.png")


def plot_best_nfmin_bar(best: pd.DataFrame, out_dir: Path, title_label: str) -> None:
    if best.empty:
        return
    data = best.copy()
    data["label"] = data["device"] + " " + data["topology"]
    colors = [style_for(row.device, row.topology)["color"] for row in data.itertuples()]
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.bar(data["label"], data["NFmin_dB"], color=colors)
    annotate_bars(ax, data["NFmin_dB"], "{:.4g}")
    ax.set_ylabel("Best NFmin (dB)")
    ax.set_title(f"{title_label}: Best NFmin per Device and Topology")
    ax.tick_params(axis="x", rotation=35)
    for tick in ax.get_xticklabels():
        tick.set_ha("right")
    ax.grid(axis="y", alpha=0.35)
    save_fig(out_dir / "02_best_nfmin_bar.png")


def plot_tradeoff(best: pd.DataFrame, out_dir: Path, title_label: str) -> None:
    if best.empty:
        return
    plt.figure(figsize=(8, 6))
    for (device, topology), sub in best.groupby(["device", "topology"]):
        style = style_for(device, topology)
        plt.scatter(
            sub["Pdc_mW"],
            sub["NFmin_dB"],
            s=110,
            color=style["color"],
            marker=style["marker"],
            edgecolors="black",
            linewidths=0.5,
            label=f"{device} {topology}",
        )
        for _, row in sub.iterrows():
            plt.annotate(
                row["device"].replace("nfet_", ""),
                (row["Pdc_mW"], row["NFmin_dB"]),
                textcoords="offset points",
                xytext=(5, 5),
                fontsize=8,
            )
    plt.xlabel("Power at best NFmin point (mW)")
    plt.ylabel("Best NFmin (dB)")
    plt.title(f"{title_label}: Best NFmin vs Power Tradeoff")
    plt.grid(True, alpha=0.35)
    plt.legend(fontsize=8, ncol=2)
    save_fig(out_dir / "03_best_nfmin_vs_power.png")


def plot_gmid_vs_jd(df: pd.DataFrame, out_dir: Path, title_label: str) -> None:
    plt.figure(figsize=(10, 6))
    for (device, topology), sub in df.groupby(["device", "topology"]):
        style = style_for(device, topology)
        plt.scatter(
            sub["JD_mA_per_um"],
            sub["gm_ID_1_per_V"],
            s=22,
            alpha=0.85,
            edgecolors="none",
            color=style["color"],
            marker=style["marker"],
            label=f"{device} {topology}",
        )
    plt.xscale("log")
    plt.xlabel("JD (mA/um)")
    plt.ylabel("gm/ID (1/V)")
    plt.title(f"{title_label}: gm/ID vs Current Density")
    plt.grid(True, which="both", alpha=0.35)
    plt.legend(fontsize=8, ncol=2)
    save_fig(out_dir / "04_gmid_vs_jd_all.png")


def plot_gmro_vs_jd(df: pd.DataFrame, out_dir: Path, title_label: str) -> None:
    plt.figure(figsize=(10, 6))
    for (device, topology), sub in df.groupby(["device", "topology"]):
        style = style_for(device, topology)
        plt.scatter(
            sub["JD_mA_per_um"],
            sub["gmro"],
            s=22,
            alpha=0.85,
            edgecolors="none",
            color=style["color"],
            marker=style["marker"],
            label=f"{device} {topology}",
        )
    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel("JD (mA/um)")
    plt.ylabel("gmro")
    plt.title(f"{title_label}: Intrinsic Gain vs Current Density")
    plt.grid(True, which="both", alpha=0.35)
    plt.legend(fontsize=8, ncol=2)
    save_fig(out_dir / "05_gmro_vs_jd_all.png")


def plot_sopt(
    df: pd.DataFrame,
    out_dir: Path,
    title_label: str,
    annotation_metric: str = "NFmin_dB",
) -> None:
    plt.figure(figsize=(7, 7))
    theta = np.linspace(0, 2 * np.pi, 400)
    plt.plot(np.cos(theta), np.sin(theta), "k--", linewidth=1.2, alpha=0.7)
    for (device, topology), sub in df.groupby(["device", "topology"]):
        style = style_for(device, topology)
        plt.scatter(
            sub["SOpt_real"],
            sub["SOpt_imag"],
            s=22,
            alpha=0.85,
            edgecolors="none",
            color=style["color"],
            marker=style["marker"],
            label=f"{device} {topology}",
        )
    if annotation_metric in df.columns:
        best_idx = df.groupby(["device", "topology"], dropna=False)[annotation_metric].idxmin()
        best_points = df.loc[best_idx].copy()
        for _, row in best_points.iterrows():
            style = style_for(row["device"], row["topology"])
            label = (
                f"{row['device'].replace('nfet_', '')} {row['topology']}\n"
                f"({row['SOpt_real']:.3f}, {row['SOpt_imag']:.3f})\n"
                f"|G|={row['SOpt_mag']:.3f}"
            )
            plt.scatter(
                [row["SOpt_real"]],
                [row["SOpt_imag"]],
                s=80,
                color=style["color"],
                marker=style["marker"],
                edgecolors="black",
                linewidths=0.7,
                zorder=5,
            )
            plt.annotate(
                label,
                (row["SOpt_real"], row["SOpt_imag"]),
                xytext=(6, 6),
                textcoords="offset points",
                fontsize=7,
                bbox={"boxstyle": "round,pad=0.25", "fc": "white", "ec": "0.7", "alpha": 0.85},
            )
    plt.xlabel("Re(SOpt)")
    plt.ylabel("Im(SOpt)")
    plt.title(f"{title_label}: Optimum Source Reflection Coefficient")
    plt.axis("equal")
    plt.grid(True, alpha=0.35)
    plt.legend(fontsize=8, ncol=2)
    save_fig(out_dir / "06_sopt_plane.png")


def plot_vgs_curves(df: pd.DataFrame, out_dir: Path, title_label: str) -> None:
    for (device, topology), sub in df.groupby(["device", "topology"]):
        style = style_for(device, topology)
        best_geom = (
            sub.groupby(["W_m", "L_m"])["NFmin_dB"]
            .min()
            .sort_values()
            .head(4)
            .index
        )
        plt.figure(figsize=(10, 6))
        geom_colors = plt.cm.tab10(np.linspace(0, 1, max(len(best_geom), 1)))
        line_styles = ["-", "--", "-.", ":"]
        for idx, (w_m, l_m) in enumerate(best_geom):
            curve = sub[(sub["W_m"].eq(w_m)) & (sub["L_m"].eq(l_m))]
            curve = curve.sort_values("VBIAS_set_V")
            label = f"W={w_m * 1e6:g}um L={l_m * 1e6:g}um"
            plt.plot(
                curve["VBIAS_set_V"],
                curve["NFmin_dB"],
                linewidth=2.0,
                color=geom_colors[idx],
                marker=style["marker"],
                markersize=3,
                markevery=max(len(curve) // 18, 1),
                alpha=0.95,
                linestyle=line_styles[idx % len(line_styles)],
                label=label,
            )
        plt.xlabel("Bias voltage / swept VGS target (V)")
        plt.ylabel("NFmin (dB)")
        plt.title(f"{title_label}: {device} {topology} Best Geometry NFmin Curves")
        plt.grid(True, alpha=0.35)
        plt.legend(fontsize=8)
        safe = f"{device}_{topology}".replace("/", "_").replace(" ", "_")
        save_fig(out_dir / f"07_nfmin_vs_bias_{safe}.png")


def generate_plot_set(
    df: pd.DataFrame,
    out_dir: Path,
    title_label: str,
    group_file: list[str],
    annotation_metric: str,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    best_by_file = best_rows(df, group_file, "NFmin_dB")
    plot_nfmin_vs_jd(df, out_dir, title_label)
    plot_best_nfmin_bar(best_by_file, out_dir, title_label)
    plot_tradeoff(best_by_file, out_dir, title_label)
    plot_gmid_vs_jd(df, out_dir, title_label)
    plot_gmro_vs_jd(df, out_dir, title_label)
    plot_sopt(df, out_dir, title_label, annotation_metric)
    plot_vgs_curves(df, out_dir, title_label)


def format_value(value: object) -> str:
    if isinstance(value, (float, np.floating)):
        if not np.isfinite(value):
            return "nan"
        return f"{value:.6g}"
    return str(value)


def format_table(df: pd.DataFrame, columns: list[str]) -> str:
    if df.empty:
        return "(no rows)"
    table = df[columns].copy()
    formatted = table.applymap(format_value)
    widths = {
        col: max(len(col), formatted[col].astype(str).map(len).max())
        for col in formatted.columns
    }

    header = "  ".join(col.ljust(widths[col]) for col in formatted.columns)
    rule = "  ".join("-" * widths[col] for col in formatted.columns)
    rows = [
        "  ".join(str(row[col]).ljust(widths[col]) for col in formatted.columns)
        for _, row in formatted.iterrows()
    ]
    return "\n".join([header, rule, *rows])


def write_text_reports(
    df: pd.DataFrame,
    rejected: pd.DataFrame,
    best_file: pd.DataFrame,
    best_geom: pd.DataFrame,
    best_score: pd.DataFrame,
    out_dir: Path,
    filters: dict[str, float],
) -> None:
    best_overall = best_file.sort_values("NFmin_dB").head(16)
    note_cols = [
        "device",
        "topology",
        "W_m",
        "L_m",
        "VBIAS_set_V",
        "JD_mA_per_um",
        "Pdc_mW",
        "gm_ID_1_per_V",
        "gmro",
        "Rin_or_inv_gm_Ohm",
        "NFmin_dB",
        "NF_dB",
        "Rn_Ohm",
        "SOpt_real",
        "SOpt_imag",
    ]

    geom_cols = [
        "device",
        "topology",
        "W_m",
        "L_m",
        "VDS_set_V",
        "VBIAS_set_V",
        "JD_mA_per_um",
        "Pdc_mW",
        "gm_ID_1_per_V",
        "gmro",
        "Rin_or_inv_gm_Ohm",
        "NFmin_dB",
        "NF_dB",
        "Rn_Ohm",
        "SOpt_real",
        "SOpt_imag",
        "score",
        "design_score",
    ]

    shortlist_cols = [
        "device",
        "topology",
        "W_m",
        "L_m",
        "VDS_set_V",
        "VBIAS_set_V",
        "JD_mA_per_um",
        "Pdc_mW",
        "gm_S",
        "gm_ID_1_per_V",
        "gmro",
        "Rin_or_inv_gm_Ohm",
        "NFmin_dB",
        "NF_dB",
        "Rn_Ohm",
        "SOpt_real",
        "SOpt_imag",
        "SOpt_mag",
        "design_score",
    ]

    lines = [
        "LNA SWEEP ANALYSIS NOTES",
        "=" * 24,
        "",
        "How to read this:",
        "- These reports use only practical LNA operating points after filtering.",
        "- NFmin_dB compares the intrinsic noise potential of each device/bias.",
        "- NF_dB depends on the present source/load setup, so do not rank only by NF_dB.",
        "- For common-gate candidates, Rin_or_inv_gm_Ohm near 50 ohm is easier to match.",
        "- For common-source candidates, use SOpt_real, SOpt_imag, and Rn_Ohm for input matching.",
        "- The score is a practical helper: lower is better. It penalizes high NFmin, power, Rn, poor CG 50-ohm fit, and low gm/ID.",
        "- The design_score is stricter for real design choice: lower actual NF_dB, lower power, lower Rn, and less edge-like SOpt are preferred.",
        "",
        "Filter settings:",
        f"- gm_S >= {filters['min_gm_s']:.6g} S",
        f"- ID_A >= {filters['min_id_a']:.6g} A",
        f"- Pdc_mW >= {filters['min_pdc_mw']:.6g} mW",
        f"- Rin_or_inv_gm_Ohm <= {filters['max_inv_gm_ohm']:.6g} ohm",
        f"- CG Rin range: {filters['cg_min_rin_ohm']:.6g} to {filters['cg_max_rin_ohm']:.6g} ohm",
        f"- Usable points: {len(df)}",
        f"- Rejected points: {len(rejected)}",
        "",
        "BEST OVERALL POINTS BY NFMIN",
        "-" * 29,
        "",
        format_table(best_overall, note_cols),
        "",
        "PRACTICAL NEXT STEP",
        "-" * 19,
        "",
        "Start with the top NFmin candidates, then reject points with unrealistic power, poor gmro, or hard-to-match SOpt/Rin.",
    ]
    (out_dir / "summary_best_overall.txt").write_text("\n".join(lines), encoding="utf-8")

    by_device_lines = [
        "BEST POINT PER DEVICE/TOPOLOGY",
        "=" * 30,
        "",
        format_table(best_file.sort_values("NFmin_dB"), note_cols),
        "",
    ]
    (out_dir / "summary_best_by_device_topology.txt").write_text(
        "\n".join(by_device_lines), encoding="utf-8"
    )

    geom_lines = [
        "BEST NFMIN POINT PER GEOMETRY",
        "=" * 29,
        "",
        format_table(best_geom.sort_values("NFmin_dB"), geom_cols),
        "",
    ]
    (out_dir / "summary_best_by_geometry.txt").write_text(
        "\n".join(geom_lines), encoding="utf-8"
    )

    score_lines = [
        "BEST PRACTICAL SCORE PER GEOMETRY",
        "=" * 33,
        "",
        format_table(best_score.sort_values("score"), geom_cols),
        "",
    ]
    (out_dir / "summary_practical_score.txt").write_text(
        "\n".join(score_lines), encoding="utf-8"
    )

    shortlist_idx = df.groupby(
        ["device", "topology", "W_m", "L_m", "VDS_set_V"], dropna=False
    )["design_score"].idxmin()
    shortlist = df.loc[shortlist_idx].sort_values("design_score").head(40)
    shortlist_lines = [
        "DESIGN SHORTLIST",
        "=" * 16,
        "",
        "This table is usually more useful than pure NFmin ranking.",
        "It ranks usable points by actual NF_dB, power, Rn, SOpt_mag, CG Rin fit, and gm.",
        "Only the best bias point per device/topology/geometry is shown.",
        "For a 50-ohm LNA, start from the top candidates here, then verify S11, gain, NF, stability, and linearity in the full LNA.",
        "",
        format_table(shortlist, shortlist_cols),
        "",
    ]
    (out_dir / "summary_design_shortlist.txt").write_text(
        "\n".join(shortlist_lines), encoding="utf-8"
    )

    reject_cols = [
        "filter_reason",
        "device",
        "topology",
        "W_m",
        "L_m",
        "VBIAS_set_V",
        "ID_A",
        "Pdc_mW",
        "gm_S",
        "Rin_or_inv_gm_Ohm",
        "NFmin_dB",
        "NF_dB",
    ]
    reason_counts = rejected["filter_reason"].value_counts().reset_index()
    reason_counts.columns = ["filter_reason", "count"]
    rejected_sample = rejected.sort_values(["filter_reason", "NFmin_dB"]).head(80)
    reject_lines = [
        "FILTER REPORT",
        "=" * 13,
        "",
        "Rejected point counts:",
        "",
        format_table(reason_counts, ["filter_reason", "count"]),
        "",
        "First rejected examples, sorted by reason and NFmin:",
        "",
        format_table(rejected_sample, reject_cols),
        "",
        "Important: very low NFmin at tiny gm/current is expected to be rejected. A transistor with gm in nS/uS range is not an LNA input device.",
    ]
    (out_dir / "summary_filter_report.txt").write_text(
        "\n".join(reject_lines), encoding="utf-8"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "files",
        nargs="*",
        help="Sweep text files. If omitted, the default eight files are used.",
    )
    parser.add_argument(
        "-o",
        "--out-dir",
        default=str(DEFAULT_RESULTS_DIR / "lna_sweep_analysis"),
        help="Output directory for plots and text summaries.",
    )
    parser.add_argument(
        "--min-gm-s",
        type=float,
        default=DEFAULT_FILTERS["min_gm_s"],
        help="Minimum gm in siemens for an LNA-usable point.",
    )
    parser.add_argument(
        "--min-id-a",
        type=float,
        default=DEFAULT_FILTERS["min_id_a"],
        help="Minimum drain current in amperes for an LNA-usable point.",
    )
    parser.add_argument(
        "--min-pdc-mw",
        type=float,
        default=DEFAULT_FILTERS["min_pdc_mw"],
        help="Minimum DC power in mW for an LNA-usable point.",
    )
    parser.add_argument(
        "--max-inv-gm-ohm",
        type=float,
        default=DEFAULT_FILTERS["max_inv_gm_ohm"],
        help="Maximum 1/gm or CG Rin estimate allowed in ohms.",
    )
    parser.add_argument(
        "--cg-min-rin-ohm",
        type=float,
        default=DEFAULT_FILTERS["cg_min_rin_ohm"],
        help="Minimum allowed common-gate Rin estimate in ohms.",
    )
    parser.add_argument(
        "--cg-max-rin-ohm",
        type=float,
        default=DEFAULT_FILTERS["cg_max_rin_ohm"],
        help="Maximum allowed common-gate Rin estimate in ohms.",
    )
    args = parser.parse_args()

    paths = [Path(p) for p in args.files] if args.files else discover_default_files()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    frames = []
    for path in paths:
        print(f"Reading {path}")
        frames.append(read_sweep(path))

    df = pd.concat(frames, ignore_index=True)
    raw_df = add_scores(df)

    filters = {
        "min_gm_s": args.min_gm_s,
        "min_id_a": args.min_id_a,
        "min_pdc_mw": args.min_pdc_mw,
        "max_inv_gm_ohm": args.max_inv_gm_ohm,
        "cg_min_rin_ohm": args.cg_min_rin_ohm,
        "cg_max_rin_ohm": args.cg_max_rin_ohm,
    }
    usable_df, rejected_df = apply_lna_filter(df, **filters)
    if usable_df.empty:
        raise SystemExit(
            "All points were rejected by the practical LNA filter.\n"
            "Try relaxing thresholds, for example:\n"
            "  python3 analyze_lna_sweeps.py --min-gm-s 1e-4 --max-inv-gm-ohm 10000\n"
        )
    usable_df = add_scores(usable_df)

    group_file = ["device", "topology", "source_file"]
    group_geom = ["device", "topology", "W_m", "L_m", "VDS_set_V"]

    best_by_file = best_rows(usable_df, group_file, "NFmin_dB")
    best_by_geom = best_rows(usable_df, group_geom, "NFmin_dB")
    best_by_score = best_rows(usable_df, group_geom, "score")

    generate_plot_set(
        raw_df,
        out_dir / "plots_all_data",
        "All Raw Sweep Points",
        group_file,
        "NFmin_dB",
    )
    generate_plot_set(
        usable_df,
        out_dir / "plots_filtered_usable",
        "Filtered Usable LNA Points",
        group_file,
        "design_score",
    )
    write_text_reports(
        usable_df,
        rejected_df,
        best_by_file,
        best_by_geom,
        best_by_score,
        out_dir,
        filters,
    )

    print()
    print(f"Done. Results written to: {out_dir.resolve()}")
    print(f"Usable points: {len(usable_df)}")
    print(f"Rejected points: {len(rejected_df)}")
    print("Plots written to plots_all_data/ and plots_filtered_usable/.")
    print("Open summary_best_overall.txt first, then summary_filter_report.txt.")


if __name__ == "__main__":
    main()
